### ISSUE TITLE
The playground needs to be restructured

### ISSUE THREAD

**Issue by yzh990918** [onu-ui/onu-ui#100]
### Description

I'm going to refactor the onu-ui playground like:

![image](https://user-images.githubusercontent.com/46418596/199903210-cf26da77-373e-4223-a7d6-26249cf9f9aa.png)

**Comment by zyyv** [comment]
Yes, that's exactly what I thought.

**Comment by yzh990918** [comment]
> Yes, that's exactly what I thought.

But before this can begin, the issue(#96 ) needs to be resolved in time to re-release npm.

**Comment by baiwusanyu-c** [comment]
I wrote a playground project for onu-ui, but because onu-ui is not stable now, there are still many problems in playground.
see:
 https://onu-ui-playground.netlify.app/
https://github.com/baiwusanyu-c/onu-ui-playground

**Comment by yzh990918** [comment]
> I wrote a playground project for onu-ui, but because onu-ui is not stable now, there are still many problems in playground. see: https://onu-ui-playground.netlify.app/

Nice!

**Comment by yzh990918** [comment]
> I wrote a playground project for onu-ui, but because onu-ui is not stable now, there are still many problems in playground. see: https://onu-ui-playground.netlify.app/ https://github.com/baiwusanyu-c/onu-ui-playground

Create a pull request? Our subsequent maintenance may be more convenient 😄 .

**Comment by baiwusanyu-c** [comment]
> > I wrote a playground project for onu-ui, but because onu-ui is not stable now, there are still many problems in playground. see: https://onu-ui-playground.netlify.app/ https://github.com/baiwusanyu-c/onu-ui-playground
> 
> Create a pull request? Our subsequent maintenance may be more convenient 😄 .

Okay, wait a few days, I think I can refine it a bit first

**Comment by yzh990918** [comment]
Try the latest version.

**Comment by baiwusanyu-c** [comment]
> Try the latest version.
The style of the message is still lost, is it something I wrote wrong?
[see](https://codesandbox.io/p/github/baiwusanyu-c/test-uno/csb-sebguv/draft/crimson-firefly?selection=%5B%7B%22endColumn%22%3A31%2C%22endLineNumber%22%3A12%2C%22startColumn%22%3A31%2C%22startLineNumber%22%3A12%7D%5D&file=%2Fpackage.json&workspace=%257B%2522activeFileId%2522%253A%2522cla96yqwu0000l2ja8gwdatju%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fpackage.json%2522%252C%2522%252Fsrc%252FApp.vue%2522%252C%2522%252Fpnpm-lock.yaml%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522claaefwme00kg356smkxxcvq9%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522claaefsw000fk356sh63vzrne%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

**Comment by yzh990918** [comment]
> > Try the latest version.
> > The style of the message is still lost, is it something I wrote wrong?
> > [see](https://codesandbox.io/p/github/baiwusanyu-c/test-uno/csb-sebguv/draft/crimson-firefly?selection=%5B%7B%22endColumn%22%3A31%2C%22endLineNumber%22%3A12%2C%22startColumn%22%3A31%2C%22startLineNumber%22%3A12%7D%5D&file=%2Fpackage.json&workspace=%257B%2522activeFileId%2522%253A%2522cla96yqwu0000l2ja8gwdatju%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fpackage.json%2522%252C%2522%252Fsrc%252FApp.vue%2522%252C%2522%252Fpnpm-lock.yaml%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522claaefwme00kg356smkxxcvq9%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522claaefsw000fk356sh63vzrne%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

I will refactor this component.

**Comment by yzh990918** [comment]
> > Try the latest version.
> > The style of the message is still lost, is it something I wrote wrong?
> > [see](https://codesandbox.io/p/github/baiwusanyu-c/test-uno/csb-sebguv/draft/crimson-firefly?selection=%5B%7B%22endColumn%22%3A31%2C%22endLineNumber%22%3A12%2C%22startColumn%22%3A31%2C%22startLineNumber%22%3A12%7D%5D&file=%2Fpackage.json&workspace=%257B%2522activeFileId%2522%253A%2522cla96yqwu0000l2ja8gwdatju%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fpackage.json%2522%252C%2522%252Fsrc%252FApp.vue%2522%252C%2522%252Fpnpm-lock.yaml%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522claaefwme00kg356smkxxcvq9%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522claaefsw000fk356sh63vzrne%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

The latest version has fixed this problem, you can try it.

**Comment by baiwusanyu-c** [comment]
The style of the message is still lost 🤣 
icon color、shadow、height
<img width="606" alt="截屏2022-11-12 15 58 50" src="https://user-images.githubusercontent.com/32354856/201464782-9e429901-2c04-4e77-8217-ecf8cf85ec0d.png">

<img width="606" alt="截屏2022-11-12 16 02 14" src="https://user-images.githubusercontent.com/32354856/201464855-2bc93347-6aa8-4155-ae5f-f681c609b67b.png">

[see](https://codesandbox.io/p/github/baiwusanyu-c/test-uno/draft/fast-dew?file=%2Funocss.config.ts&selection=%5B%7B%22endColumn%22%3A30%2C%22endLineNumber%22%3A19%2C%22startColumn%22%3A7%2C%22startLineNumber%22%3A19%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cladmsxxj000gl1fqbuvtdyms%2522%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522cladmt13z00aa3b6hmpqs24w9%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522cladmtcj000kh3b6h7tf4bnko%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cladmt6sc00e73b6hkxzkucgr%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

**Comment by yzh990918** [comment]
> The style of the message is still lost 🤣 icon color、shadow、height <img alt="截屏2022-11-12 15 58 50" width="606" src="https://user-images.githubusercontent.com/32354856/201464782-9e429901-2c04-4e77-8217-ecf8cf85ec0d.png">
> 
> <img alt="截屏2022-11-12 16 02 14" width="606" src="https://user-images.githubusercontent.com/32354856/201464855-2bc93347-6aa8-4155-ae5f-f681c609b67b.png">
> 
> [see](https://codesandbox.io/p/github/baiwusanyu-c/test-uno/draft/fast-dew?file=%2Funocss.config.ts&selection=%5B%7B%22endColumn%22%3A30%2C%22endLineNumber%22%3A19%2C%22startColumn%22%3A7%2C%22startLineNumber%22%3A19%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cladmsxxj000gl1fqbuvtdyms%2522%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522cladmt13z00aa3b6hmpqs24w9%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522cladmtcj000kh3b6h7tf4bnko%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cladmt6sc00e73b6hkxzkucgr%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

You might need add this line of code to `main.ts`

<img width="403" alt="image" src="https://user-images.githubusercontent.com/46418596/201560331-09811e6b-dce5-4c53-a05f-348a7a2f1bc9.png">

**Comment by baiwusanyu-c** [comment]
![image](https://user-images.githubusercontent.com/32354856/201580101-362b3cc8-f0ed-446b-8a58-c1ee8f849eee.png)
But why the icon still has no color? 🤣
