### ISSUE TITLE
[BUG] - The HMR doesn't work any more after OnuUI used

### ISSUE THREAD

**Issue by Heromyth** [onu-ui/onu-ui#102]
### Describe the bug

All the *.vue pages in brower will not be updated automatically after using OnuUI in main.ts like this
```ts
app.use(OnuUI);
```
Once a vue page that using any OnuUI element like OButton is actived, all the *.vue pages also will not be updated automatically any more.
```vue
<OButton >Button</OButton>
```

I can see the page is updated by vite:
```sh
11:17:02 [vite] page reload src/main.ts
11:17:45 [vite] hmr update /src/views/AboutView.vue
```

### Reproduction

https://github.com/Dedal378/vue3-template

### System Info

```Shell
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 32.20 GB / 47.01 GB
    Container: Yes
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.16.0 - /usr/local/bin/npm
  Browsers:
    Firefox: 102.4.0esr
  npmPackages:
    vue: ^3.2.41 => 3.2.41
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/onu-ui/onu-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://onu-ui.vercel.app/).
- [X] Check that there isn't [already an issue](https://github.com/onu-ui/onu-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a OnuUI issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yzh990918** [comment]
Thanks for the feedback, we will fix it in the next release.
