### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by yzh990918** [onu-ui/onu-ui#103]
### Description

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/46418596/200228438-58b57662-4372-4758-9b39-9e3f9a76f433.png">

When I try the latest package, I don't know why this file in the dist package is referenced in the same way as before. Is there something wrong.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/46418596/200228752-7c8ef544-af5e-497d-90a4-61a581dd0e7f.png">

Local packaging is fine, This is a real headache.

**Comment by yzh990918** [comment]
I suggest local buid first, then locally package a stable version of the package and publish it directly to npm.

**Comment by yzh990918** [comment]
Could you please add a publishing permission to my npm account? I think it has wasted a lot of precious time to deal with this problem @zyyv 🥲.  My npm usename is `yangzhihao03`, npm email is `251205668@qq.com`.

**Comment by zyyv** [comment]
> Could you please add a publishing permission to my npm account? I think it has wasted a lot of precious time to deal with this problem @zyyv 🥲. My npm usename is `yangzhihao03`, npm email is `251205668@qq.com`.

加我微信 私聊

**Comment by yzh990918** [comment]
> 

ok

**Comment by yzh990918** [comment]
> > Could you please add a publishing permission to my npm account? I think it has wasted a lot of precious time to deal with this problem @zyyv 🥲. My npm usename is `yangzhihao03`, npm email is `251205668@qq.com`.
> 
> 加我微信 私聊 微信号：zhu-_-chris

1
