### ISSUE TITLE
[BUG] - Some component usage issues

### ISSUE THREAD

**Issue by baiwusanyu-c** [onu-ui/onu-ui#107]
### Describe the bug

I recently wanted to contribute a playground, but encountered problems during the writing process
1.An error will be reported when a single component of the component library is imported and used

Taking the button component as an example, a single manual import or automatic import using a plug-in will result in an error
![image](https://user-images.githubusercontent.com/32354856/200745824-fb5e9c41-69c0-44a5-b319-42a4e8744e75.png)

2.The absence of class makes some style variables unavailable.
Take the message component as an example：
![image](https://user-images.githubusercontent.com/32354856/200745966-a3435ef4-4f4f-465b-a950-e2ba8c899566.png)

### Reproduction

https://codesandbox.io/p/github/baiwusanyu-c/test-uno/csb-sebguv/draft/crimson-firefly?file=%2Fsrc%2FApp.vue&workspace=%257B%2522activeFileId%2522%253A%2522cla96yqwv0002l2ja51clf2jr%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522cla96zwjg000m356l327b8t79%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

### System Info

```Shell
I don't know if it's a beta version problem, or if I have some preset configuration errors
both mac and win
Version 1.0.10-beta.5
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/onu-ui/onu-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://onu-ui.vercel.app/).
- [X] Check that there isn't [already an issue](https://github.com/onu-ui/onu-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a OnuUI issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yzh990918** [comment]
Thank you for your reply, this is indeed a very serious bug. We are trying to find a way to solve this problem. We have initially located a bug in our packaging. If you have any ideas, you can share them with us at any time.
