### ISSUE TITLE
作者打算让社区一起做么？

### ISSUE THREAD

**Issue by SnowingFox** [onu-ui/onu-ui#11]
因为我也挺想加入开发的，毕竟unocss + vue搭配起来真的很爽

但是你好像没说需要做哪些组件，想贡献也无从下手，可以在README写个todo，让社区一起贡献完善吗？

真的很期待unocss的ui

**Comment by zyyv** [comment]
hhh 谢谢关注，可以的。
但是我这个现在还算是小玩具，不算是官方的UI库，基建还没有搭好，也还在慢慢摸索，后面我会列出todo list
你也可以提出 issue，pr 参与建设
再次感谢🙏

**Comment by baiwusanyu-c** [comment]
看了看项目目前打包脚本还不够完善，也没有加入单测，文档站点也还没有，chris近期会有相关的todoList吗

**Comment by zyyv** [comment]
> 看了看项目目前打包脚本还不够完善，也没有加入单测，文档站点也还没有，chris近期会有相关的todoList吗

确实不够完善，还在持续优化基建，架子没搭好，不方便pr。近一周可能没有，感谢关注🙏

**Comment by SnowingFox** [comment]
> > 看了看项目目前打包脚本还不够完善，也没有加入单测，文档站点也还没有，chris近期会有相关的todoList吗
> 
> 确实不够完善，还在持续优化基建，架子没搭好，不方便pr。近一周可能没有，感谢关注🙏

我看你的架构有点像element-plus，不知道我猜的对不对😂

**Comment by zyyv** [comment]
> 

确实有借鉴😅 看了很多ui库的基建，还在学习中😂

**Comment by priority3** [comment]
哈哈 同上 希望可以参与😁
