### ISSUE TITLE
Grey border of Popup when dark color scheme

### ISSUE THREAD

**Issue by tkzt** [onu-ui/onu-ui#131]
### Description

I'm actually not sure is this an issue or not👇

![image](https://user-images.githubusercontent.com/38272264/213421414-5159e868-63eb-44ff-ab67-f4243d3f2e42.png)

**Comment by yzh990918** [comment]
This will be fixed in the next release.

**Comment by yzh990918** [comment]
I am sorry that I have been too busy to deal with your question recently，it fixed in #131. Thanks!
