### ISSUE TITLE
Style(Collapse): Collapse Component border-bottom is strange

### ISSUE THREAD

**Issue by zhangmo8** [onu-ui/onu-ui#133]
### Description

In OnuUI, the border-bottom is the Title shown with the  Folding panel Close. 
But in other  Ui Libray, The Collapse Component border-bottom will be with the animation from the Folding panel.

I don't know if this is a bug. But I think it's strange

**Comment by yzh990918** [comment]
This is a problem left over when writing the component, we will refactor the collapse component when we start the component writing task later, and this problem will be fixed at that time, thank you for your careful discovery ❤️.

**Comment by zhangmo8** [comment]
hhhh, can i pr for that?

**Comment by yzh990918** [comment]
> hhhh, can i pr for that?

sure
