### ISSUE TITLE
[BUG]: Playground HMR not working

### ISSUE THREAD

**Issue by yzh990918** [onu-ui/onu-ui#137]
### Description

I want to try to run `Playground` in the local dev environment, but I found that the libraries that `Playground` depends on are all CDN links, which means that Playground cannot sense changes in the component library, and I also found a problem, when I modify 'welcome.vue' with the editor, `Playground` cannot be refresh  @baiwusanyu have time to help see if not,hhh.

You can try the minimal implementation locally by`pnpm play` .

**Comment by baiwusanyu-c** [comment]
ok i'll check it out soon @yzh990918

**Comment by baiwusanyu-c** [comment]
about HMR, I can't reproduce it, can you provide a demo @yzh990918 
[link](https://onu.zyob.top/play/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IENvbXAgZnJvbSAnLi9Db21wLnZ1ZSdcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gICAgIDxDb21wPjwvQ29tcD5cbjwvdGVtcGxhdGU+XG5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiQ29tcC52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvYWRhd2R3YXJkZGRsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxpbnB1dCB2LW1vZGVsPVwibXNnXCI+XG48L3RlbXBsYXRlPiIsIl9vIjp7fX0=)

**Comment by yzh990918** [comment]
This is a bug in the local debugging environment and cannot be minimally implemented.
1. RUN `pnpm dev`
2. RUN `pnpm play`
3. Edit `Playground/src/template/welcome.vue` or edit onu components, Vite HMR not working
4. The dependencies collected by the development environment are also CDNs

**Comment by yzh990918** [comment]
The latest version of the component library is `1.0.13-beta.2`, but Latest gets `1.0.13-beta.1`.
[link](https://onu.zyob.top/play?onu=latest&vue=latest#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IG9udVVJLCB7IE9NZXNzYWdlIGFzIG1lc3NhZ2UgfSBmcm9tICdvbnUtdWknXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gT251IFVJIScpXG5jb25zdCBjaGVja1ZhbCA9IHJlZih0cnVlKVxuY29uc3QgbXYgPSByZWYodHJ1ZSlcbmNvbnN0IGF2YXRhclNyY3MgPSAnaHR0cHM6Ly9naXRodWIuY29tL3p5eXYucG5nJ1xuY29uc3Qgb3BlbiA9ICgpID0+IHtcbiAgbWVzc2FnZSh7XG4gICAgY29udGVudDogJ0hlbGxvIE9udVVJIScsXG4gICAgY2xvc2FibGU6IHRydWUsXG4gIH0pXG59XG5cbmNvbnN0IGNsYXNzTmFtZSA9ICdkYXJrJ1xuY29uc3QgaXNEYXJrID0gcmVmKGZhbHNlKVxuXG5jb25zdCB0b2dnbGVUaGVtZSA9ICgpID0+IHtcbiAgaWYgKHR5cGVvZiB3aW5kb3cgIT09ICd1bmRlZmluZWQnKSB7XG4gICAgY29uc3Qgcm9vdENscyA9IGRvY3VtZW50LmRvY3VtZW50RWxlbWVudC5jbGFzc0xpc3RcbiAgICBpc0RhcmsudmFsdWUgPSAhaXNEYXJrLnZhbHVlXG4gICAgaWYgKGlzRGFyay52YWx1ZSlcbiAgICAgIHJvb3RDbHMuYWRkKGNsYXNzTmFtZSlcbiAgICBlbHNlXG4gICAgICByb290Q2xzLnJlbW92ZShjbGFzc05hbWUpXG4gIH1cbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgcC01IHNwYWNlLXktMz5cbiAgICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgICA8ZGl2IGlubGluZS1mbGV4IEBjbGljaz1cInRvZ2dsZVRoZW1lKClcIj5cbiAgICAgIFRvb2dsZSBUaGVtZTpcbiAgICAgIDxvLWljb25cbiAgICAgICAgdi1zaG93PVwiaXNEYXJrXCIgaC01IGN1cnNvci1wb2ludGVyIHctNSBteC00IG5hbWU9XCJpLWNhcmJvbi1tb29uXCJcbiAgICAgIC8+XG4gICAgICA8by1pY29uIHYtc2hvdz1cIiFpc0RhcmtcIiBoLTUgdy01IGN1cnNvci1wb2ludGVyIG14LTQgbmFtZT1cImktY2FyYm9uLXN1blwiIC8+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBmc2N3IHNwYWNlLXgtND5cbiAgICAgIDxvLWJhZGdlIDp2YWx1ZT1cIjEwMFwiPlxuICAgICAgICA8by1idXR0b24gdHlwZT1cInByaW1hcnlcIj5cbiAgICAgICAgICA8dGVtcGxhdGUgI2ljb24+XG4gICAgICAgICAgICA8ZGl2IGktY2FyYm9uLXNoYXJlIHRleHQtc20gLz5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICAgIFByaW1hcnlcbiAgICAgICAgPC9vLWJ1dHRvbj5cbiAgICAgIDwvby1iYWRnZT5cbiAgICAgIDxvLWJ1dHRvbiB0eXBlPVwic3VjY2Vzc1wiIEBjbGljaz1cIm9wZW5cIj5cbiAgICAgICAgU2hvdyBNZXNzYWdlXG4gICAgICA8L28tYnV0dG9uPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgZnNjdyBzcGFjZS14LTI+XG4gICAgICA8by1jaGVja2JveCBvPVwid2hpdGVcIiBsYWJlbD1cIlZ1ZVwiIHNpemU9XCJsZ1wiIGljb249XCJpLWxvZ29zLXZ1ZVwiIC8+XG4gICAgICA8by1jaGVja2JveCB2LW1vZGVsPVwiY2hlY2tWYWxcIiBsYWJlbD1cImJhc2ljIHVzZVwiIG8tcHJpbWFyeSAvPlxuICAgIDwvZGl2PlxuXG4gICAgPGRpdiBmc2N3IGdhcC0yPlxuICAgICAgPG8tc3dpdGNoIHYtbW9kZWw9XCJtdlwiIG89XCJwcmltYXJ5XCIgLz5cbiAgICAgIDxvLXN3aXRjaCB2LW1vZGVsPVwibXZcIiB2IG89XCJzZWNvbmRhcnlcIiAvPlxuICAgICAgPG8tc3dpdGNoIHYtbW9kZWw9XCJtdlwiIG89XCJzdWNjZXNzXCIgLz5cbiAgICAgIDxvLXN3aXRjaCB2LW1vZGVsPVwibXZcIiBvPVwid2FybmluZ1wiIC8+XG4gICAgICA8by1zd2l0Y2ggdi1tb2RlbD1cIm12XCIgbz1cImVycm9yXCIgLz5cbiAgICAgIDxvLXN3aXRjaCB2LW1vZGVsPVwibXZcIiBvPVwiaW5mb1wiIC8+XG4gICAgPC9kaXY+XG5cbiAgICA8ZGl2IGZzY3cgZ2FwLTI+XG4gICAgICA8by1hdmF0YXIgOnNyYz1cImF2YXRhclNyY3NcIiAvPlxuICAgIDwvZGl2PlxuXG4gICAgPGRpdiBmc2N3IGdhcC0yPlxuICAgICAgPG8tdGFnIHR5cGU9XCJwcmltYXJ5XCI+XG4gICAgICAgIFByaW1hcnlcbiAgICAgIDwvby10YWc+XG4gICAgICA8by10YWcgdHlwZT1cInNlY29uZGFyeVwiPlxuICAgICAgICBTZWNvbmRhcnlcbiAgICAgIDwvby10YWc+XG4gICAgICA8by10YWcgdHlwZT1cInN1Y2Nlc3NcIj5cbiAgICAgICAgU3VjY2Vzc1xuICAgICAgPC9vLXRhZz5cbiAgICAgIDxvLXRhZyB0eXBlPVwid2FybmluZ1wiPlxuICAgICAgICBXYXJuaW5nXG4gICAgICA8L28tdGFnPlxuICAgICAgPG8tdGFnIHR5cGU9XCJlcnJvclwiPlxuICAgICAgICBFcnJvclxuICAgICAgPC9vLXRhZz5cbiAgICAgIDxvLXRhZyB0eXBlPVwiaW5mb1wiPlxuICAgICAgICBJbmZvXG4gICAgICA8L28tdGFnPlxuICAgICAgPG8tdGFnIHR5cGU9XCJwcmltYXJ5XCIgYmctY29sb3I9XCIjMWFiYzljXCI+XG4gICAgICAgIEN1c3RvbS1CZ1xuICAgICAgPC9vLXRhZz5cbiAgICA8L2Rpdj5cblxuICAgIDxwPlZ1ZSB7eyB2dWVWZXJzaW9uIH19PC9wPlxuICAgIDxwPm9udVVJIHt7IG9udVVJLnZlcnNpb24gfX08L3A+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuYm9keSB7XG4gIGNvbG9yOiB2YXIoLS1vbnUtY29sb3JzLXRleHQpO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1vbnUtY29sb3JzLWJhY2tncm91bmQpO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by yzh990918** [comment]
Now the link copied by the production environment is a bit too long, such as this one https://onu.zyob.top/play?onu=latest&vue=latest#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IG9udVVJLCB7IE9NZXNzYWdlIGFzIG1lc3NhZ2UgfSBmcm9tICdvbnUtdWknXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gT251IFVJIScpXG5jb25zdCBjaGVja1ZhbCA9IHJlZih0cnVlKVxuY29uc3QgbXYgPSByZWYodHJ1ZSlcbmNvbnN0IGF2YXRhclNyY3MgPSAnaHR0cHM6Ly9naXRodWIuY29tL3p5eXYucG5nJ1xuY29uc3Qgb3BlbiA9ICgpID0+IHtcbiAgbWVzc2FnZSh7XG4gICAgY29udGVudDogJ0hlbGxvIE9udVVJIScsXG4gICAgY2xvc2FibGU6IHRydWUsXG4gIH0pXG59XG5cbmNvbnN0IGNsYXNzTmFtZSA9ICdkYXJrJ1xuY29uc3QgaXNEYXJrID0gcmVmKGZhbHNlKVxuXG5jb25zdCB0b2dnbGVUaGVtZSA9ICgpID0+IHtcbiAgaWYgKHR5cGVvZiB3aW5kb3cgIT09ICd1bmRlZmluZWQnKSB7XG4gICAgY29uc3Qgcm9vdENscyA9IGRvY3VtZW50LmRvY3VtZW50RWxlbWVudC5jbGFzc0xpc3RcbiAgICBpc0RhcmsudmFsdWUgPSAhaXNEYXJrLnZhbHVlXG4gICAgaWYgKGlzRGFyay52YWx1ZSlcbiAgICAgIHJvb3RDbHMuYWRkKGNsYXNzTmFtZSlcbiAgICBlbHNlXG4gICAgICByb290Q2xzLnJlbW92ZShjbGFzc05hbWUpXG4gIH1cbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgcC01IHNwYWNlLXktMz5cbiAgICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgICA8ZGl2IGlubGluZS1mbGV4IEBjbGljaz1cInRvZ2dsZVRoZW1lKClcIj5cbiAgICAgIFRvb2dsZSBUaGVtZTpcbiAgICAgIDxvLWljb25cbiAgICAgICAgdi1zaG93PVwiaXNEYXJrXCIgaC01IGN1cnNvci1wb2ludGVyIHctNSBteC00IG5hbWU9XCJpLWNhcmJvbi1tb29uXCJcbiAgICAgIC8+XG4gICAgICA8by1pY29uIHYtc2hvdz1cIiFpc0RhcmtcIiBoLTUgdy01IGN1cnNvci1wb2ludGVyIG14LTQgbmFtZT1cImktY2FyYm9uLXN1blwiIC8+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBmc2N3IHNwYWNlLXgtND5cbiAgICAgIDxvLWJhZGdlIDp2YWx1ZT1cIjEwMFwiPlxuICAgICAgICA8by1idXR0b24gdHlwZT1cInByaW1hcnlcIj5cbiAgICAgICAgICA8dGVtcGxhdGUgI2ljb24+XG4gICAgICAgICAgICA8ZGl2IGktY2FyYm9uLXNoYXJlIHRleHQtc20gLz5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICAgIFByaW1hcnlcbiAgICAgICAgPC9vLWJ1dHRvbj5cbiAgICAgIDwvby1iYWRnZT5cbiAgICAgIDxvLWJ1dHRvbiB0eXBlPVwic3VjY2Vzc1wiIEBjbGljaz1cIm9wZW5cIj5cbiAgICAgICAgU2hvdyBNZXNzYWdlXG4gICAgICA8L28tYnV0dG9uPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgZnNjdyBzcGFjZS14LTI+XG4gICAgICA8by1jaGVja2JveCBvPVwid2hpdGVcIiBsYWJlbD1cIlZ1ZVwiIHNpemU9XCJsZ1wiIGljb249XCJpLWxvZ29zLXZ1ZVwiIC8+XG4gICAgICA8by1jaGVja2JveCB2LW1vZGVsPVwiY2hlY2tWYWxcIiBsYWJlbD1cImJhc2ljIHVzZVwiIG8tcHJpbWFyeSAvPlxuICAgIDwvZGl2PlxuXG4gICAgPGRpdiBmc2N3IGdhcC0yPlxuICAgICAgPG8tc3dpdGNoIHYtbW9kZWw9XCJtdlwiIG89XCJwcmltYXJ5XCIgLz5cbiAgICAgIDxvLXN3aXRjaCB2LW1vZGVsPVwibXZcIiB2IG89XCJzZWNvbmRhcnlcIiAvPlxuICAgICAgPG8tc3dpdGNoIHYtbW9kZWw9XCJtdlwiIG89XCJzdWNjZXNzXCIgLz5cbiAgICAgIDxvLXN3aXRjaCB2LW1vZGVsPVwibXZcIiBvPVwid2FybmluZ1wiIC8+XG4gICAgICA8by1zd2l0Y2ggdi1tb2RlbD1cIm12XCIgbz1cImVycm9yXCIgLz5cbiAgICAgIDxvLXN3aXRjaCB2LW1vZGVsPVwibXZcIiBvPVwiaW5mb1wiIC8+XG4gICAgPC9kaXY+XG5cbiAgICA8ZGl2IGZzY3cgZ2FwLTI+XG4gICAgICA8by1hdmF0YXIgOnNyYz1cImF2YXRhclNyY3NcIiAvPlxuICAgIDwvZGl2PlxuXG4gICAgPGRpdiBmc2N3IGdhcC0yPlxuICAgICAgPG8tdGFnIHR5cGU9XCJwcmltYXJ5XCI+XG4gICAgICAgIFByaW1hcnlcbiAgICAgIDwvby10YWc+XG4gICAgICA8by10YWcgdHlwZT1cInNlY29uZGFyeVwiPlxuICAgICAgICBTZWNvbmRhcnlcbiAgICAgIDwvby10YWc+XG4gICAgICA8by10YWcgdHlwZT1cInN1Y2Nlc3NcIj5cbiAgICAgICAgU3VjY2Vzc1xuICAgICAgPC9vLXRhZz5cbiAgICAgIDxvLXRhZyB0eXBlPVwid2FybmluZ1wiPlxuICAgICAgICBXYXJuaW5nXG4gICAgICA8L28tdGFnPlxuICAgICAgPG8tdGFnIHR5cGU9XCJlcnJvclwiPlxuICAgICAgICBFcnJvclxuICAgICAgPC9vLXRhZz5cbiAgICAgIDxvLXRhZyB0eXBlPVwiaW5mb1wiPlxuICAgICAgICBJbmZvXG4gICAgICA8L28tdGFnPlxuICAgICAgPG8tdGFnIHR5cGU9XCJwcmltYXJ5XCIgYmctY29sb3I9XCIjMWFiYzljXCI+XG4gICAgICAgIEN1c3RvbS1CZ1xuICAgICAgPC9vLXRhZz5cbiAgICA8L2Rpdj5cblxuICAgIDxwPlZ1ZSB7eyB2dWVWZXJzaW9uIH19PC9wPlxuICAgIDxwPm9udVVJIHt7IG9udVVJLnZlcnNpb24gfX08L3A+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuYm9keSB7XG4gIGNvbG9yOiB2YXIoLS1vbnUtY29sb3JzLXRleHQpO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1vbnUtY29sb3JzLWJhY2tncm91bmQpO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==

**Comment by yzh990918** [comment]
@baiwusanyu-c  That's probably the problem at the moment.

**Comment by baiwusanyu-c** [comment]
ok let me sum it up
1. All dependencies come from CDN, so the code being developed locally cannot be used in the playground during development.
2. vite lost hot update in playground.
3. The url is a bit long (maybe consider streamlining dependencies or replacing with a more streamlined algorithm).
4. <del>See switching failure for the same version (for example: 1.0.13-beta.2 -> 1.0.13-beta.1 may display an incorrect version).</del>(It may be a problem when the package is released)

**Comment by yzh990918** [comment]
还有两处Typescript类型匹配报错也可以看看 
1. `playground/src/App.vue`
![image](https://user-images.githubusercontent.com/46418596/223045665-6dcfee1a-015f-45f0-afe8-f5a807c76865.png)
2. `playground/src/components/Header.vue`
![image](https://user-images.githubusercontent.com/46418596/223045886-75eda4f6-992a-4259-88db-7b0f0085e8fb.png)

**Comment by baiwusanyu-c** [comment]
It's strange about point 4, the version obtained using latest is not v1.0.13-beta.2
![image](https://user-images.githubusercontent.com/32354856/223059052-9b062885-4c53-484f-aaee-5b22330f7c1d.png)
we maybe need to check the released package @yzh990918 
https://cdn.jsdelivr.net/npm/onu-ui@1.0.13-beta.2/dist/onu-ui.js

**Comment by yzh990918** [comment]
> It's strange about point 4, the version obtained using latest is not v1.0.13-beta.2 ![image](https://user-images.githubusercontent.com/32354856/223059052-9b062885-4c53-484f-aaee-5b22330f7c1d.png) we maybe need to check the released package @yzh990918 https://cdn.jsdelivr.net/npm/onu-ui@1.0.13-beta.2/dist/onu-ui.js

I seem to know the reason, it may be caused by the local release package on my side. sry

**Comment by yzh990918** [comment]
> It's strange about point 4, the version obtained using latest is not v1.0.13-beta.2 ![image](https://user-images.githubusercontent.com/32354856/223059052-9b062885-4c53-484f-aaee-5b22330f7c1d.png) we maybe need to check the released package @yzh990918 https://cdn.jsdelivr.net/npm/onu-ui@1.0.13-beta.2/dist/onu-ui.js

I rereleased the version, but latest is still 1.0.13-beta.1. It seems that there is a delay in the CDN. I think you should change your strategy. When I switch versions it seems to work fine [link](https://onu.zyob.top/play/?onu=1.0.13-beta.7&vue=latest#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IG9udVVJLCB7IE9NZXNzYWdlIGFzIG1lc3NhZ2UgfSBmcm9tICdvbnUtdWknXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gT251IFVJIScpXG5jb25zdCBjaGVja1ZhbCA9IHJlZih0cnVlKVxuY29uc3QgbXYgPSByZWYodHJ1ZSlcbmNvbnN0IGF2YXRhclNyY3MgPSAnaHR0cHM6Ly9naXRodWIuY29tL3p5eXYucG5nJ1xuY29uc3Qgb3BlbiA9ICgpID0+IHtcbiAgbWVzc2FnZSh7XG4gICAgY29udGVudDogJ0hlbGxvIE9udVVJIScsXG4gICAgY2xvc2FibGU6IHRydWUsXG4gIH0pXG59XG5cbmNvbnN0IGNsYXNzTmFtZSA9ICdkYXJrJ1xuY29uc3QgaXNEYXJrID0gcmVmKGZhbHNlKVxuXG5jb25zdCB0b2dnbGVUaGVtZSA9ICgpID0+IHtcbiAgaWYgKHR5cGVvZiB3aW5kb3cgIT09ICd1bmRlZmluZWQnKSB7XG4gICAgY29uc3Qgcm9vdENscyA9IGRvY3VtZW50LmRvY3VtZW50RWxlbWVudC5jbGFzc0xpc3RcbiAgICBpc0RhcmsudmFsdWUgPSAhaXNEYXJrLnZhbHVlXG4gICAgaWYgKGlzRGFyay52YWx1ZSlcbiAgICAgIHJvb3RDbHMuYWRkKGNsYXNzTmFtZSlcbiAgICBlbHNlXG4gICAgICByb290Q2xzLnJlbW92ZShjbGFzc05hbWUpXG4gIH1cbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgcC01IHNwYWNlLXktMz5cbiAgICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgICA8ZGl2IGlubGluZS1mbGV4IEBjbGljaz1cInRvZ2dsZVRoZW1lKClcIj5cbiAgICAgIFRvb2dsZSBUaGVtZTpcbiAgICAgIDxvLWljb25cbiAgICAgICAgdi1zaG93PVwiaXNEYXJrXCIgaC01IGN1cnNvci1wb2ludGVyIHctNSBteC00IG5hbWU9XCJpLWNhcmJvbi1tb29uXCJcbiAgICAgIC8+XG4gICAgICA8by1pY29uIHYtc2hvdz1cIiFpc0RhcmtcIiBoLTUgdy01IGN1cnNvci1wb2ludGVyIG14LTQgbmFtZT1cImktY2FyYm9uLXN1blwiIC8+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBmc2N3IHNwYWNlLXgtND5cbiAgICAgIDxvLWJhZGdlIDp2YWx1ZT1cIjEwMFwiPlxuICAgICAgICA8by1idXR0b24gdHlwZT1cInByaW1hcnlcIj5cbiAgICAgICAgICA8dGVtcGxhdGUgI2ljb24+XG4gICAgICAgICAgICA8ZGl2IGktY2FyYm9uLXNoYXJlIHRleHQtc20gLz5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICAgIFByaW1hcnlcbiAgICAgICAgPC9vLWJ1dHRvbj5cbiAgICAgIDwvby1iYWRnZT5cbiAgICAgIDxvLWJ1dHRvbiB0eXBlPVwic3VjY2Vzc1wiIEBjbGljaz1cIm9wZW5cIj5cbiAgICAgICAgU2hvdyBNZXNzYWdlXG4gICAgICA8L28tYnV0dG9uPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgZnNjdyBzcGFjZS14LTI+XG4gICAgICA8by1jaGVja2JveCBvPVwid2hpdGVcIiBsYWJlbD1cIlZ1ZVwiIHNpemU9XCJsZ1wiIGljb249XCJpLWxvZ29zLXZ1ZVwiIC8+XG4gICAgICA8by1jaGVja2JveCB2LW1vZGVsPVwiY2hlY2tWYWxcIiBsYWJlbD1cImJhc2ljIHVzZVwiIG8tcHJpbWFyeSAvPlxuICAgIDwvZGl2PlxuXG4gICAgPGRpdiBmc2N3IGdhcC0yPlxuICAgICAgPG8tc3dpdGNoIHYtbW9kZWw9XCJtdlwiIG89XCJwcmltYXJ5XCIgLz5cbiAgICAgIDxvLXN3aXRjaCB2LW1vZGVsPVwibXZcIiB2IG89XCJzZWNvbmRhcnlcIiAvPlxuICAgICAgPG8tc3dpdGNoIHYtbW9kZWw9XCJtdlwiIG89XCJzdWNjZXNzXCIgLz5cbiAgICAgIDxvLXN3aXRjaCB2LW1vZGVsPVwibXZcIiBvPVwid2FybmluZ1wiIC8+XG4gICAgICA8by1zd2l0Y2ggdi1tb2RlbD1cIm12XCIgbz1cImVycm9yXCIgLz5cbiAgICAgIDxvLXN3aXRjaCB2LW1vZGVsPVwibXZcIiBvPVwiaW5mb1wiIC8+XG4gICAgPC9kaXY+XG5cbiAgICA8ZGl2IGZzY3cgZ2FwLTI+XG4gICAgICA8by1hdmF0YXIgOnNyYz1cImF2YXRhclNyY3NcIiAvPlxuICAgIDwvZGl2PlxuXG4gICAgPGRpdiBmc2N3IGdhcC0yPlxuICAgICAgPG8tdGFnIHR5cGU9XCJwcmltYXJ5XCI+XG4gICAgICAgIFByaW1hcnlcbiAgICAgIDwvby10YWc+XG4gICAgICA8by10YWcgdHlwZT1cInNlY29uZGFyeVwiPlxuICAgICAgICBTZWNvbmRhcnlcbiAgICAgIDwvby10YWc+XG4gICAgICA8by10YWcgdHlwZT1cInN1Y2Nlc3NcIj5cbiAgICAgICAgU3VjY2Vzc1xuICAgICAgPC9vLXRhZz5cbiAgICAgIDxvLXRhZyB0eXBlPVwid2FybmluZ1wiPlxuICAgICAgICBXYXJuaW5nXG4gICAgICA8L28tdGFnPlxuICAgICAgPG8tdGFnIHR5cGU9XCJlcnJvclwiPlxuICAgICAgICBFcnJvclxuICAgICAgPC9vLXRhZz5cbiAgICAgIDxvLXRhZyB0eXBlPVwiaW5mb1wiPlxuICAgICAgICBJbmZvXG4gICAgICA8L28tdGFnPlxuICAgICAgPG8tdGFnIHR5cGU9XCJwcmltYXJ5XCIgYmctY29sb3I9XCIjMWFiYzljXCI+XG4gICAgICAgIEN1c3RvbS1CZ1xuICAgICAgPC9vLXRhZz5cbiAgICA8L2Rpdj5cblxuICAgIDxwPlZ1ZSB7eyB2dWVWZXJzaW9uIH19PC9wPlxuICAgIDxwPm9udVVJIHt7IG9udVVJLnZlcnNpb24gfX08L3A+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuYm9keSB7XG4gIGNvbG9yOiB2YXIoLS1vbnUtY29sb3JzLXRleHQpO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1vbnUtY29sb3JzLWJhY2tncm91bmQpO1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

**Comment by yzh990918** [comment]
https://fastly.jsdelivr.net/npm/onu-ui@latest/dist/onu-ui.js This file seems to never be updated @baiwusanyu-c

**Comment by baiwusanyu-c** [comment]
> https://fastly.jsdelivr.net/npm/onu-ui@latest/dist/onu-ui.js This file seems to never be updated @baiwusanyu-c

It's updated, the latest is 1.0.13-beta.7
![截屏2023-03-06 21 33 49](https://user-images.githubusercontent.com/32354856/223124758-e9d36821-ddbc-4a0d-98f9-efc7f274edc8.png)

**Comment by yzh990918** [comment]
> > https://fastly.jsdelivr.net/npm/onu-ui@latest/dist/onu-ui.js This file seems to never be updated @baiwusanyu-c
> 
> It's updated, the latest is 1.0.13-beta.7 ![截屏2023-03-06 21 33 49](https://user-images.githubusercontent.com/32354856/223124758-e9d36821-ddbc-4a0d-98f9-efc7f274edc8.png)

![image](https://user-images.githubusercontent.com/46418596/223129889-5ea5e9f0-f8b3-4aa9-8037-98245137e83c.png)

**Comment by baiwusanyu-c** [comment]
This is very strange! Hahaha🤣, maybe a certain source pointed to by his CDN node has not been updated, but I see that it has been updated

**Comment by yzh990918** [comment]
> This is very strange! Hahaha🤣, maybe a certain source pointed to by his CDN node has not been updated, but I see that it has been updated

It seems that there is a cache, and now there is another problem that I need to have the ability to jump all demo components to the playground in the document like element ui, which you are more familiar with, and see if you need to wrap a `usePlayground` hook to do this work 😃

**Comment by yzh990918** [comment]
@baiwusanyu-c  I don't quite understand how to get the real link in the playground by passing in the code param, You are familiar with this piece, can you help take a look ❤️

**Comment by baiwusanyu-c** [comment]
> @baiwusanyu-c I don't quite understand how to get the real link in the playground by passing in the code param, You are familiar with this piece, can you help take a look ❤️

Do you have Chris WeChat, you can contact me through him and discuss further

**Comment by baiwusanyu-c** [comment]
> 2. vite lost hot update in playground.
For the second point, edit `playground/src/template/welcome.vue`, it is expected that the content of the browser will not be updated, because `playground` first takes the parameter of the url as the file content, so if the content is edited Modified in the browser, even if vite will send the changes to the browser, the playground will not change due to changes in hot update content @yzh990918
