### ISSUE TITLE
Button transition animation takes too long

### ISSUE THREAD

**Issue by IceyWu** [onu-ui/onu-ui#14]
按钮hover和active时有0.2s的过渡，就我个人体验而言我觉得时间有点长，给我造成一种卡顿的感觉，个人觉得可以不要这个0.2s的过渡或者过渡时间相对短一点

**Comment by zyyv** [comment]
好的 可以   你觉得多少合适呢？ transition 默认是150ms

**Comment by IceyWu** [comment]
个人感觉没有可能体验更好一点

**Comment by zyyv** [comment]
> 个人感觉没有可能体验更好一点

我觉得还好，没有过渡 我觉得有点生硬

**Comment by IceyWu** [comment]
嗯嗯，也对
