### ISSUE TITLE
[BUG] - HMR: package/preset

### ISSUE THREAD

**Issue by wzc520pyfm** [onu-ui/onu-ui#149]
### Describe the bug

When I was developing, I found that after editing `package/preset/src/shortcuts` , the newly edited content will not take effect in the browser page.
1. `pnpm run dev`
2. `pnpm run example`
3. edit file in `package/preset/src/shortcuts`
4. HMR filed

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/onu-ui/onu-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://onu-ui.vercel.app/).
- [X] Check that there isn't [already an issue](https://github.com/onu-ui/onu-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a OnuUI issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yzh990918** [comment]
It seems that the local on my side can trigger the rebuild 😅 .
