### ISSUE TITLE
O-Card divider not shown with custom header slot

### ISSUE THREAD

**Issue by npdev453** [onu-ui/onu-ui#157]
### Description

```vue
<OCard divider>
 <template #header> header </template>
 <template #default> default </template> 
 <template #extra> extra </template>
 <template #actions> actions </template>
</OCard>
```
<img width="874" alt="image" src="https://user-images.githubusercontent.com/1401931/229385677-f2e54f71-7f1f-4e11-a204-5b59f2a79eaa.png">

**Comment by yzh990918** [comment]
Generally, the `header` is customized, and it is incorrect to customize the `extra` again. Only one of the two can be customized.

**Comment by yzh990918** [comment]
fixed https://github.com/onu-ui/onu-ui/commit/8252789fc77da75b336687ff488b4f22eee10b47
