### ISSUE TITLE
O-Text deployed documentation contains unexistient features

### ISSUE THREAD

**Issue by npdev453** [onu-ui/onu-ui#160]
### Description

Deployed documentation at official site contains unexistient features like OText component

But no way for alpha\beta package versions with it provided 

And also documentation here marked as v1.0.13 its not truth
<img width="676" alt="image" src="https://user-images.githubusercontent.com/1401931/229390866-09bdfe4d-7437-435f-9e51-2ac6beca194a.png">

**Comment by yzh990918** [comment]
Some components have not been released yet, sorry.
