### ISSUE TITLE
CodeSandbox example didnt start

### ISSUE THREAD

**Issue by npdev453** [onu-ui/onu-ui#161]
### Description

<img width="398" alt="image" src="https://user-images.githubusercontent.com/1401931/229386195-dc602174-40ea-44b6-a48f-0e8423050a08.png">

**Comment by yzh990918** [comment]
It seems to be a problem with codesandbox. I see no problem here. As soon as I share it, there is this problem.

<img width="1719" alt="image" src="https://user-images.githubusercontent.com/46418596/236107889-cd9bd83b-a4b4-4d24-a560-ae908486c066.png">

**Comment by yzh990918** [comment]
Starter origin: https://github.com/yzh990918/onu-starter
