### ISSUE TITLE
Icons coloring didnt working on stackblitz example out of box

### ISSUE THREAD

**Issue by npdev453** [onu-ui/onu-ui#162]
### Description

(o-icon coloring is realy seems to be fragile and hard to tune)

<img width="470" alt="image" src="https://user-images.githubusercontent.com/1401931/229386443-83054f1d-bd72-466a-be2f-e84ba579bbcc.png">

**Comment by wzc520pyfm** [comment]
The color property of the icon works on our playground. Can you provide minimal duplicate links on stackblitz?

https://onu.zyob.top/play/?onu=latest&vue=latest#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGdyaWQ9XCJ+IGNvbHMtOCBnYXAtNCBtZDpjb2xzLTEyIHhsOmNvbHMtMTRcIiBtIHVuLWNoaWxkcmVuPVwidGV4dC02XCI+XG4gICAgPG8taWNvbiBvLXByaW1hcnkgbmFtZT1cImktY2FyYm9uLW1vb25cIiAvPlxuICAgIDxvLWljb24gby1zZWNvbmRhcnkgbmFtZT1cImktY2FyYm9uLW1vb25cIiAvPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=

**Comment by npdev453** [comment]
@wzc520pyfm 
Playgroud is dirty, have hidden configuration, files `app.vue`, `vite.config` and `uno.config` are hidden, also if it builded from repo, they have an shadow deps from parent folder.

Code on stackblitz is more looks like `starter`

So I make only one change, just add to footer two icons with different colors:
```
 <o-icon o="error" name="i-carbon-moon" class="mr-1"></o-icon>
 <o-icon o="warn" name="i-carbon-moon" class="mr-1"></o-icon>
``` 
URL:
https://stackblitz.com/edit/onu-starter-dzjbbx?file=src/components/Footer.vue


ps: Also I got the same error when trying to configure repo first time because use whole starter example from stackblitz

**Comment by yzh990918** [comment]
@npdev453  https://onu.zyob.top/guide/install.html#custom-unocss-config You need to inject Onu's presets, then it will works.
