### ISSUE TITLE
O-Badge coloring inside button didnt work

### ISSUE THREAD

**Issue by npdev453** [onu-ui/onu-ui#164]
### Description

```vue

   <OButton 
     size="lg"
     type="primary"
     class="w-full"
   > 
     
     <OBadge o="primary"  :value="15">
        Testing 
     </OBadge>
     
  </OButton>

```

Badge should be blue but o-error styles from OButton class owerride css colors of badge by red.

Seems its not documented usage, but userfull for wide buttons with badges (like main menu or mobile menu and etc)

<img width="251" alt="image" src="https://user-images.githubusercontent.com/1401931/229389028-0c018849-59b5-4629-9d9c-f84ed0681b0b.png">

**Comment by wzc520pyfm** [comment]
You can use `o="primary"`.
```html
<o-badge o="primary" :value="100"></o-badge>
```

see: https://onu.zyob.top/play/?onu=latest&vue=latest#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGZzY3cgZ2FwLTY+XG4gICAgPG8tYmFkZ2Ugbz1cInByaW1hcnlcIiA6dmFsdWU9XCIxMDBcIj5cbiAgICAgIDxvLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIGxpZ2h0PlxuICAgICAgICBQcmltYXJ5XG4gICAgICA8L28tYnV0dG9uPlxuICAgIDwvby1iYWRnZT5cbiAgICA8by1iYWRnZSA6dmFsdWU9XCI5XCI+XG4gICAgICA8by1hdmF0YXIgY2xhc3M9XCJvLWdyYXkgZGFyay1vLSMzYTNhM2NcIiByb3VuZGVkIC8+XG4gICAgPC9vLWJhZGdlPlxuICAgIDxvLWJhZGdlIDpvPVwiY29sb3JcIiB2YWx1ZT1cImhhcHB5XCI+XG4gICAgICA8by1idXR0b24gdHlwZT1cImVycm9yXCIgbGlnaHQ+XG4gICAgICAgIEN1c3RvbSBDb2xvclxuICAgICAgPC9vLWJ1dHRvbj5cbiAgICA8L28tYmFkZ2U+XG4gICAgPG8tYmFkZ2Ugbz1cImluZm9cIiBkb3QgOnZhbHVlPVwiMTAwXCI+XG4gICAgICA8by1idXR0b24gdHlwZT1cImluZm9cIiBsaWdodD5cbiAgICAgICAgT25seSBEb3RcbiAgICAgIDwvby1idXR0b24+XG4gICAgPC9vLWJhZGdlPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwIG5hbWU9XCJPQmFkZ2VcIj5cbmNvbnN0IGNvbG9yID0gXCJ3YXJuaW5nXCJcbjwvc2NyaXB0PiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==

**Comment by npdev453** [comment]
@wzc520pyfm 
Sorry, I was missed `primary` variable in my example. (changed)

So, 
 I just drop warning example from you playground and coloring stopd to work

https://onu.zyob.top/play/?onu=latest&vue=latest#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGZzY3cgZ2FwLTY+XG4gICAgPG8tYmFkZ2Ugbz1cInByaW1hcnlcIiA6dmFsdWU9XCIxMDBcIj5cbiAgICAgIDxvLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIGxpZ2h0PlxuICAgICAgICBQcmltYXJ5XG4gICAgICA8L28tYnV0dG9uPlxuICAgIDwvby1iYWRnZT5cbiAgICBcbiAgICA8by1iYWRnZSA6dmFsdWU9XCI5XCI+XG4gICAgICA8by1hdmF0YXIgY2xhc3M9XCJvLWdyYXkgZGFyay1vLSMzYTNhM2NcIiByb3VuZGVkIC8+XG4gICAgPC9vLWJhZGdlPlxuXG4gICAgPG8tYmFkZ2Ugbz1cImluZm9cIiBkb3QgOnZhbHVlPVwiMTAwXCI+XG4gICAgICA8by1idXR0b24gdHlwZT1cImluZm9cIiBsaWdodD5cbiAgICAgICAgT25seSBEb3RcbiAgICAgIDwvby1idXR0b24+XG4gICAgPC9vLWJhZGdlPlxuICAgIFxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXAgbmFtZT1cIk9CYWRkZ2VcIj5cbjwvc2NyaXB0PiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1401931/229461960-8b2dd898-af06-4bb9-8170-a177ed798bc7.png">

**Comment by npdev453** [comment]
@yzh990918 
why its closed?

**Comment by yzh990918** [comment]
> @yzh990918 why its closed?

Sorry, I haven't understood your actual problem yet.

**Comment by npdev453** [comment]
problem detalized in
https://github.com/onu-ui/onu-ui/issues/166
