### ISSUE TITLE
作者大大，fork 项目之后，无法启动

### ISSUE THREAD

**Issue by ayangweb** [onu-ui/onu-ui#175]
作者大大，你好啊，我 fork 项目之后，启动项目的时候无法启动！

### pnpm dev
<img width="721" alt="image" src="https://user-images.githubusercontent.com/75017711/235608033-93bbb46e-8a83-47ac-9323-d1f5161117e8.png">

### pnpm docs
直接打开了空的 npm 界面！

### pnpm example
<img width="961" alt="image" src="https://user-images.githubusercontent.com/75017711/235608336-c93f79d3-a67a-47e9-aa08-9f1d2dd34c26.png">

### node 版本
<img width="341" alt="image" src="https://user-images.githubusercontent.com/75017711/235607842-3892672f-8be3-4a42-a16c-9124b0ef1821.png">

**Comment by yzh990918** [comment]
First run requires building.

**Comment by ayangweb** [comment]
> First run requires building.

感谢大佬，方便加您的联系方式吗？我有几个小问题比较困惑，可以向您请教吗？
