### ISSUE TITLE
[Feature Request] - Add a nuxt module

### ISSUE THREAD

**Issue by ProsperBao** [onu-ui/onu-ui#176]
### Clear and concise description of the problem

I want to use this component library in Nuxt, with automatic importing and tree shaking. I didn't see any relevant configuration in the code repository and documentation, only `unplugin` related information. 

### Suggested solution

 I think can be added to the component library. It can also be added to the [Nuxt repository](https://nuxt.com/modules?category=UI).

### Describe alternatives you've considered

Here is my simple code:

```typescript
import { addComponent, defineNuxtModule } from '@nuxt/kit'

const COMPONENT_LIST = [
  'OAffix',
  'OAlert',
  'OAvatar',
  'OAvatarGroup',
  'OBacktop',
  'OBadge',
  'OButton',
  'OButtonGroup',
  'OCard',
  'OCheckbox',
  'OCollapse',
  'OCollapseItem',
  'OConfigProvider',
  'OEmpty',
  'OIcon',
  'OLink',
  'OMessage',
  'OPopup',
  'OProgress',
  'ORadio',
  'ORadioGroup',
  'ORate',
  'OSwitch',
  'OTag',
  'OText',
  'OToolTip',
  'OTrigger',
]

export default defineNuxtModule({
  meta: {
    name: '@onu/nuxt',
    configKey: 'onu',
    compatibility: {
      nuxt: '^3.0.0',
    },
  },
  async setup() {
    COMPONENT_LIST.forEach((name) => {
      addComponent({
        name,
        export: name,
        filePath: 'onu-ui',
      })
    })
  },
})

```

### Screenshots or Videos

![image](https://github.com/onu-ui/onu-ui/assets/43855486/4a6d7664-ee79-4d49-8840-ab88c912e2c5)
![image](https://github.com/onu-ui/onu-ui/assets/43855486/492026c8-c8d3-41de-9c80-5e3124405f08)

**Comment by blaquewithaq** [comment]
For those who are impatient like me and want to utilize this now:

- Make sure onu-ui package is installed.
- Create a modules folder in your Nuxt project root, if you don't already have one.
- Create a new file: modules/onu-ui.ts > copy and paste in the code given by FuBaooo above.

If you have debug enabled in nuxt.config.ts, you will see the module load up

Thank you for this contribution! @FuBaooo

**Comment by ProsperBao** [comment]
Added on #177

**Comment by yzh990918** [comment]
There are still some problems with this package. I will release it after I fix it in my spare time. Thanks all guys.

**Comment by jaemo** [comment]
I'm really happy to see Nuxt support - I am trying to get it to work , however, I want to draw your attention to the instructions on https://onu.zyob.top/guide/install.html#using-modules-in-nuxt 

Right now it's not possible to install this package for the reasons mentioned on [177](https://github.com/onu-ui/onu-ui/pull/177), but the instructions are still published. 

It would be beneficial to edit them until such time that the package is ready to use, to reduce confusion  😃

**Comment by zyyv** [comment]
Thanks for your focus, our package is not perfect enough, I will take some time to update it next.
