### ISSUE TITLE
[BUG] - Something wrong in `Switch` docs 

### ISSUE THREAD

**Issue by tianxiang24** [onu-ui/onu-ui#197]
### Describe the bug

![image](https://github.com/onu-ui/onu-ui/assets/37059674/db48420c-5b62-4ec0-b3e2-072ca52d38c3)

### System Info

```Shell
https://onu.zyob.top/components/switch.html
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/onu-ui/onu-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://onu-ui.vercel.app/).
- [X] Check that there isn't [already an issue](https://github.com/onu-ui/onu-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a OnuUI issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Thanks for you focus it, and i'm refactoring those componets, i wont fix it.
