### ISSUE TITLE
@onu-ui/nuxt not published to npm

### ISSUE THREAD

**Issue by popadicbranislav** [onu-ui/onu-ui#203]
### Description

I wanted to try out the onu ui nuxt module, but it looks like it is not published.

I tried to install the package (example from docs below), searched the npm registry, but it is not there.

```bash
pnpm i @onu-ui/nuxt -D
```

Am I missing something?

**Comment by zyyv** [comment]
Sorry for that, i'm not complete it, and i not recommend use it. (WIP)
