### ISSUE TITLE
refactor-all 分支，项目无法运行

### ISSUE THREAD

**Issue by DimplesY** [onu-ui/onu-ui#205]
### Describe the bug

使用 pnpm dev 不能运行这个项目，直接报错
- node 18.19.1
- pnpm 8.15.5

![image](https://github.com/onu-ui/onu-ui/assets/51285767/1406179d-ab59-409f-b65a-0b0e9cc593fb)

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/onu-ui/onu-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://onu-ui.vercel.app/).
- [X] Check that there isn't [already an issue](https://github.com/onu-ui/onu-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a OnuUI issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
如果你想提前预览，可以分别跑两个进程。

- `cd packages/preset && pnpm dev`
- `pnpm example`

Then, open: `http://localhost:5173/`
可以实时预览，请忽略开发中的任何报错。
