### ISSUE TITLE
[BUG] - 404 on documentation site

### ISSUE THREAD

**Issue by abhishiv** [onu-ui/onu-ui#213]
### Describe the bug

Hello, great UI framework but looks like that the documentation site is broken.

https://onu.zyob.top/components/switch returns 404 as do all other links

### Reproduction

https://onu.zyob.top/components/switch

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/onu-ui/onu-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://onu-ui.vercel.app/).
- [X] Check that there isn't [already an issue](https://github.com/onu-ui/onu-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a OnuUI issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Just no documentation was provided, and most components are unavailable.

**Comment by abhishiv** [comment]
Hey @zyyv why is not planned when as you say most components are unavailable?

They are returning 404 like here https://pagespeed.web.dev/analysis/https-onu-zyob-top-components-switch/zfy8yurqsa?form_factor=mobile

**Comment by jceb** [comment]
Say again, why has this issue been closed? It's a little tricky to tell which components exist and which one don't.
