### ISSUE TITLE
Onu UI is **WIP**

### ISSUE THREAD

**Issue by zyyv** [onu-ui/onu-ui#214]
### Description

> [!WARNING]
> Onu is undergoing a large-scale refactoring, including `components`, `documents`, etc. Please do not use it in production environments.

~~Old branch: [`main-backup`](https://github.com/onu-ui/onu-ui/tree/main-backup)~~
**New branch**: [`main`](https://github.com/onu-ui/onu-ui/tree/main)

If you are developing an ecosystem related to `UnoCSS`, if `Onu UI` has any inspiration for you, we welcome any suggestions.

**Comment by wzc520pyfm** [comment]
Has onu-ui finished refactoring? Maybe we could make a list of WIP components or feature development plan to get more people involved.

**Comment by zyyv** [comment]
> Has onu-ui finished refactoring? Maybe we could make a list of WIP components or feature development plan to get more people involved.

Thank you for your attention, I don't know how to answer you. I am just developing it in my free time, not fast or slow, and I don't have any plans for the next step. 😵‍💫

**Comment by wzc520pyfm** [comment]
> > Has onu-ui finished refactoring? Maybe we could make a list of WIP components or feature development plan to get more people involved.
> 
> Thank you for your attention, I don't know how to answer you. I am just developing it in my free time, not fast or slow, and I don't have any plans for the next step. 😵‍💫
> 

I think okay, when the architecture of the project is complete, other developers can refer to the basic components (such as button) to develop other components. And then, we can list the existing components in the documentation in the WIP list(for other developers to claim to contribute). What do you think about this?

**Comment by zyyv** [comment]
@wzc520pyfm Sorry ping, I think Onu UI is ready to accept PR, if you are interested, welcome to contribute components.

You can refer to https://github.com/onu-ui/onu-ui/blob/main/CONTRIBUTING.md to get started

------

I don't write a roadmap, but you can refer to [shadcn ui](https://ui.shadcn.com/) and [daisy ui](https://daisyui.com/) to supplement any components.
