### ISSUE TITLE
Installation broken

### ISSUE THREAD

**Issue by jceb** [onu-ui/onu-ui#215]
### Describe the bug

Installing onu-ui via the command provided in the getting started guide fails due to unpublished package versions:

```sh
pnpm i -D @onu-ui/preset
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @onu-ui/utils@1.1.1

This error happened while installing the dependencies of @onu-ui/preset@1.1.1

The latest release of @onu-ui/utils is "1.0.14-beta.2".

If you need the full list of all 31 published versions run "$ pnpm view @onu-ui/utils versions".
Progress: resolved 641, reused 549, downloaded 0, added 0
```

### Reproduction

pnpm i -D @onu-ui/preset

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/onu-ui/onu-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://onu-ui.vercel.app/).
- [X] Check that there isn't [already an issue](https://github.com/onu-ui/onu-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a OnuUI issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
You can try to install：
```bash
pnpm add https://pkg.pr.new/onu-ui/onu-ui/@onu-ui/preset@216
```

`@onu-ui/preset` currently does not have many components, it can only provide you with a simple preview.

**Comment by oluceps** [comment]
> You can try to install：
> 
> ```shell
> pnpm add https://pkg.pr.new/onu-ui/onu-ui/@onu-ui/preset@216
> ```
> 
> `@onu-ui/preset` currently does not have many components, it can only provide you with a simple preview.

But it
```
> pnpm add https://pkg.pr.new/onu-ui/onu-ui/@onu-ui/preset@216
 ERR_PNPM_FETCH_404  GET https://pkg.pr.new/onu-ui/onu-ui/@onu-ui/preset@216: Not Found - 404

This error happened while installing a direct dependency of /home/elen/Some

No authorization header was set for the request.
Progress: resolved 43, reused 43, downloaded 0, added 0
```

**Comment by zyyv** [comment]
Sorry for that, i create quickly [release](https://github.com/onu-ui/onu-ui/releases/tag/v1.1.2). Welcome to preview!
