### ISSUE TITLE
作者探讨个问题

### ISSUE THREAD

**Issue by yzh990918** [onu-ui/onu-ui#23]
我尝试 fork 项目，并编写了card组件，编写完了 unocss 的 preset shortcuts，发现最后打包并不能将新增加的 card 的 shortcuts 打包进style.css, 这很困惑我 ， 其他的配置均没有动，能帮忙看看吗

fork仓库地址：https://github.com/251205668/onu-ui

**Comment by yzh990918** [comment]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/46418596/186898576-1b3854b4-c526-4aeb-831f-432b2c16e882.png">

**Comment by zyyv** [comment]
好的 感谢🙏。 你也可以提个pr上来，我们一起看看。

**Comment by yzh990918** [comment]
> 好的 感谢🙏。 你也可以提个pr上来，我们一起看看。

感谢回复，pr 已经提了
