### ISSUE TITLE
dev error

### ISSUE THREAD

**Issue by priority3** [onu-ui/onu-ui#35]
我在运行`pnpm run dev` 后 抛出了这样error，但是我debug了半天好像并没有发现原因😢
![image](https://user-images.githubusercontent.com/75966543/188259295-ba16fc47-0525-4ed2-9fa9-046a7d321f62.png)

**Comment by yzh990918** [comment]
> 我在运行`pnpm run dev` 后 抛出了这样error，但是我debug了半天好像并没有发现原因😢 ![image](https://user-images.githubusercontent.com/75966543/188259295-ba16fc47-0525-4ed2-9fa9-046a7d321f62.png)

There is no window test computer in hand, delete the node_modules and lock files and try to install again.
Additional information:
- Node Version: `v14.19.3`
- pnpm Version `7.5.0`

**Comment by priority3** [comment]
> > 我在运行`pnpm run dev` 后 抛出了这样error，但是我debug了半天好像并没有发现原因😢 ![image](https://user-images.githubusercontent.com/75966543/188259295-ba16fc47-0525-4ed2-9fa9-046a7d321f62.png)
> 
> There is no window test computer in hand, delete the node_modules and lock files and try to install again. Additional information:
> 
> * Node Version: `v14.19.3`
> * pnpm Version `7.5.0`

Thanks for your reply,I change the Node version and pnpm version as same as these, than delete node_modules and lock files,after install and `pnpm run build`, but same error.Let me see if it is caused by other reasons.

**Comment by priority3** [comment]
I found the solution，My guess is that tsup can't recognize some parameter problems after `--onsuccess`, so I need to do some escape. Of course, this may be friendly on `MAC`, but it may be a problem on `Windows`. Of course, it may not recognize the contents outside the double quotation marks
so , I have some change in `package.json`
```json
"stub": "tsup --watch --onSuccess \"pnpm run --filter=components stub\""
```

**Comment by yzh990918** [comment]
> 

good job!

**Comment by yzh990918** [comment]
> I found the solution，My guess is that tsup can't recognize some parameter problems after `--onsuccess`, so I need to do some escape. Of course, this may be friendly on `MAC`, but it may be a problem on `Windows`. Of course, it may not recognize the contents outside the double quotation marks so , I have some change in `package.json`
> 
> ```json
> "stub": "tsup --watch --onSuccess \"pnpm run --filter=components stub\""
> ```

good job!
