### ISSUE TITLE
Vitest Error: Failed to resolve entry for package

### ISSUE THREAD

**Issue by yzh990918** [onu-ui/onu-ui#40]
After the update, it seems that the component unit test cannot work normally. If you have time, you can look at this problem 😘@chris-zhu 

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/46418596/188532358-643e353b-06ae-4daf-810b-15f919387530.png">

**Comment by zyyv** [comment]
😅 It works fine on my local.
<img width="640" alt="image" src="https://user-images.githubusercontent.com/42139754/188535746-7d91b670-b3c9-4828-b75c-81d96d7bcf16.png">

**Comment by zyyv** [comment]
It's also failed in CI, i'm going to check .
