### ISSUE TITLE
New componet:Rate

### ISSUE THREAD

**Issue by baiwusanyu-c** [onu-ui/onu-ui#61]
![截屏2022-09-18 13 37 49](https://user-images.githubusercontent.com/32354856/190887489-b415ccc2-1131-44e4-9761-81d86f1ef3a2.png)

Props

| Attribute  | Description                            | Type       | Accepted Values | Default   |
|------------|----------------------------------------|------------|-----------------|-----------|
| modelValue | binding value                          | `number`   |                 | `0`       |
| max        | max rating score                       | `number`   |                 | `5`       |
| readonly   | whether Rate is read-only              | `boolean`  |                 | `false`   |
| allow-half | whether picking half start is allowed  | `boolean`  |                 | `false`   |
| color      | selected icon color                    | `string`   |                 | `warning` |
| void-color | unselected icon color                  | `string`   |                 | `-`       |
| show-text  | text displayed at the end of the star  | `string`   |                 | `-`       |

 Event

| Name   | Parameters            | Description                          |
|--------|-----------------------|--------------------------------------|
| change | value after changing  | Triggers when rate value is changed  |

**Comment by priority3** [comment]
Maybe, the issue should be closed @baiwusanyu-c
