### ISSUE TITLE
⏸️ Stop !!! 

### ISSUE THREAD

**Issue by zyyv** [onu-ui/onu-ui#72]
Let's pause the input of new components, we should optimize the current components and workflow first, and then consider new components.
I think so many issues should be optimized, we can review other component code mutually.

**Comment by yzh990918** [comment]
agree

**Comment by yzh990918** [comment]
有个打包的问题，不知道为什么`components` 下有几个 UI 组件用 vite 打包之后丢失了声明文件，也没看出什么影响打包的问题

**Comment by yzh990918** [comment]
How is it going? I have some problems with the build. I plan to use rollup to reconstruct the build script system, but I am still learning rollup 😀 @chris-zhu .

**Comment by zyyv** [comment]
> How is it going? I have some problems with the build. I plan to use rollup to reconstruct the build script system, but I am still learning rollup 😀 @chris-zhu .

Hi, sorry for not following this project for a long time due to the holiday and the busy days before.
emm...  I'm not good at rollup😅, i pefer the vite. If we use rollup, those plugins might have an effect.

**Comment by yzh990918** [comment]
> > How is it going? I have some problems with the build. I plan to use rollup to reconstruct the build script system, but I am still learning rollup 😀 @chris-zhu .
> 
> Hi, sorry for not following this project for a long time due to the holiday and the busy days before. emm... I'm not good at rollup😅, i pefer the vite. If we use rollup, those plugins might have an effect.

Do you have any plans for the next step? Maybe it would be better to make a list.

**Comment by yzh990918** [comment]
> 有个打包的问题，不知道为什么`components` 下有几个 UI 组件用 vite 打包之后丢失了声明文件，也没看出什么影响打包的问题
@chris-zhu @priority3  这个问题间接的影响了我在做新的打包方案中组件库声明文件的构建，使用vite build 组件过程中报错了, 大佬们可以看下不
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/46418596/195496069-05c73ba2-b529-4a64-9465-9f4520db63c4.png">
<img width="313" alt="image" src="https://user-images.githubusercontent.com/46418596/195496590-8b43fb29-8a5c-4669-ac67-0638e68e275a.png">

**Comment by yzh990918** [comment]
> > 有个打包的问题，不知道为什么`components` 下有几个 UI 组件用 vite 打包之后丢失了声明文件，也没看出什么影响打包的问题
> > @chris-zhu @priority3  这个问题间接的影响了我在做新的打包方案中组件库声明文件的构建，使用vite build 组件过程中报错了, 大佬们可以看下不
> 
> <img alt="image" width="1511" src="https://user-images.githubusercontent.com/46418596/195496069-05c73ba2-b529-4a64-9465-9f4520db63c4.png">
> 
> <img alt="image" width="313" src="https://user-images.githubusercontent.com/46418596/195496590-8b43fb29-8a5c-4669-ac67-0638e68e275a.png">

The final discovery is that vite-plugin-dts‘s bug : https://github.com/qmhc/vite-plugin-dts/issues/125.

**Comment by zyyv** [comment]
Nice catch, forgive me that use it casually.😅

**Comment by zyyv** [comment]
> Do you have any plans for the next step? Maybe it would be better to make a list.

I spend time to maintain UnoCSS cause for a long time no update.😅 I found that writing components requires a lot of care.

As you said the next step, I want optimize the existing components and add dark mode fot them.

**Comment by yzh990918** [comment]
> Nice catch, forgive me that use it casually.😅



> > > 有个打包的问题，不知道为什么`components` 下有几个 UI 组件用 vite 打包之后丢失了声明文件，也没看出什么影响打包的问题
> > > @chris-zhu @priority3  这个问题间接的影响了我在做新的打包方案中组件库声明文件的构建，使用vite build 组件过程中报错了, 大佬们可以看下不
> > 
> > 
> > <img alt="image" width="1511" src="https://user-images.githubusercontent.com/46418596/195496069-05c73ba2-b529-4a64-9465-9f4520db63c4.png">
> > <img alt="image" width="313" src="https://user-images.githubusercontent.com/46418596/195496590-8b43fb29-8a5c-4669-ac67-0638e68e275a.png">
> 
> The final discovery is that vite-plugin-dts‘s bug : [qmhc/vite-plugin-dts#125](https://github.com/qmhc/vite-plugin-dts/issues/125).

**Comment by yzh990918** [comment]
> > > 有个打包的问题，不知道为什么`components` 下有几个 UI 组件用 vite 打包之后丢失了声明文件，也没看出什么影响打包的问题
> > > @chris-zhu @priority3  这个问题间接的影响了我在做新的打包方案中组件库声明文件的构建，使用vite build 组件过程中报错了, 大佬们可以看下不
> > 
> > 
> > <img alt="image" width="1511" src="https://user-images.githubusercontent.com/46418596/195496069-05c73ba2-b529-4a64-9465-9f4520db63c4.png">
> > <img alt="image" width="313" src="https://user-images.githubusercontent.com/46418596/195496590-8b43fb29-8a5c-4669-ac67-0638e68e275a.png">
> 
> The final discovery is that vite-plugin-dts‘s bug : [qmhc/vite-plugin-dts#125](https://github.com/qmhc/vite-plugin-dts/issues/125).

The problem with the declaration file is still not completely solved, I will continue to check

**Comment by yzh990918** [comment]
> > > > 有个打包的问题，不知道为什么`components` 下有几个 UI 组件用 vite 打包之后丢失了声明文件，也没看出什么影响打包的问题
> > > > @chris-zhu @priority3  这个问题间接的影响了我在做新的打包方案中组件库声明文件的构建，使用vite build 组件过程中报错了, 大佬们可以看下不
> > > 
> > > 
> > > <img alt="image" width="1511" src="https://user-images.githubusercontent.com/46418596/195496069-05c73ba2-b529-4a64-9465-9f4520db63c4.png">
> > > <img alt="image" width="313" src="https://user-images.githubusercontent.com/46418596/195496590-8b43fb29-8a5c-4669-ac67-0638e68e275a.png">
> > 
> > 
> > The final discovery is that vite-plugin-dts‘s bug : [qmhc/vite-plugin-dts#125](https://github.com/qmhc/vite-plugin-dts/issues/125).
> 
> The problem with the declaration file is still not completely solved, I will continue to check

Maby [vue-tsc](https://github.com/johnsoncodehk/volar/tree/master/vue-language-tools/vue-tsc) is more suitable for Vue single-file declarations that package setup script.
<img width="297" alt="image" src="https://user-images.githubusercontent.com/46418596/195520458-da97219f-4c1b-42cc-a11a-d88d0d4aa288.png">

**Comment by yzh990918** [comment]
> Nice catch, forgive me that use it casually.😅 

Finally i upgrade the vite-plugin-dts to ^1.6.5 fixed it @chris-zhu.
This the production files screenshots:
![image](https://user-images.githubusercontent.com/46418596/195577263-827445ab-ef1c-4e54-825c-17366bd4e127.png)

**Comment by yzh990918** [comment]
Some existing problems are sorted out：
- [x] Currently the component library build does not export the declaration related file, I will fix this part.
- [ ] At present, the component library only supports on-demand import. The full import test found that there was a problem, and Vue did not successfully register the component library fully.
- [ ] The component library provides the props for the ide code. Currently, the props can only be used with volar, but the props cannot be used for possible values, such as type and size.
- [ ] Dark mode is not yet compatible.
- [x] Some components mistakenly use the UnoCSS selector and package this part of unmatch.
- [ ] Component documentation and global documentation need to be refined.
- [ ] Component libraries support theme configuration.
- [ ] The component library supports multiple language switching.

**Comment by priority3** [comment]
> Some existing problems are sorted out：
> 
> * [ ]  Currently the component library build does not export the declaration related file, I will fix this part.
> * [ ]  At present, the component library only supports on-demand import. The full import test found that there was a problem, and Vue did not successfully register the component library fully.
> * [ ]  The component library provides the props for the ide code. Currently, the props can only be used with volar, but the props cannot be used for possible values, such as type and size.
> * [ ]  Dark mode is not yet compatible.
> * [ ]  Some components mistakenly use the UnoCSS selector and package this part of unmatch.
> * [ ]  Component documentation and global documentation need to be refined.

wow , sorry I just see it now when you ping me before, I will try to study and solve these 🤣

**Comment by yzh990918** [comment]
I found another weird ci bug,same as last time,guys help😅! @chris-zhu @priority3 
https://github.com/yzh990918/onu-ui/actions/runs/3249269890/jobs/5331478692

**Comment by priority3** [comment]
I find you can delete `vue` dependencies in `components` packages, which can work , I find `message` and `collapse` are did by myself and they are work well ,which  just import all function of vue to deal with test , but this is not long-term plan , I should study this 🙄@yzh990918

**Comment by yzh990918** [comment]
> I find you can delete `vue` dependencies in `components` packages, which can work , I find `message` and `collapse` are did by myself and they are work well ,which just import all function of vue to deal with test , but this is not long-term plan , I should study this 🙄@yzh990918

Got it!

**Comment by yzh990918** [comment]
> I find you can delete `vue` dependencies in `components` packages, which can work , I find `message` and `collapse` are did by myself and they are work well ,which just import all function of vue to deal with test , but this is not long-term plan , I should study this 🙄@yzh990918

It seems not work: https://github.com/yzh990918/onu-ui/actions/runs/3258309804/jobs/5353432959

**Comment by yzh990918** [comment]
Unit testing of components often fails, and I think it's worth exploring why it always fails. Local environment  often runs successfully.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/46418596/196047728-0ae4b453-19c8-4918-a1a4-37bbf80b6ec4.png">

**Comment by yzh990918** [comment]
> Some existing problems are sorted out：
> 
> * [x]  Currently the component library build does not export the declaration related file, I will fix this part.
> * [ ]  At present, the component library only supports on-demand import. The full import test found that there was a problem, and Vue did not successfully register the component library fully.
> * [ ]  The component library provides the props for the ide code. Currently, the props can only be used with volar, but the props cannot be used for possible values, such as type and size.
> * [ ]  Dark mode is not yet compatible.
> * [x]  Some components mistakenly use the UnoCSS selector and package this part of unmatch.
> * [ ]  Component documentation and global documentation need to be refined.

Question 2 needs help to look at, I can't solve it for the time being，this is a serious bug where components cannot be registered globally. @chris-zhu @priority3

**Comment by yzh990918** [comment]
> 

The only way to register global components is to load OnuResolver with resolvers from vue-components. Obviously that's not reasonable. I think this only works as an onu-ui's ability to load components on demand, and global registration of components should succeed without configuring it.

<img width="910" alt="image" src="https://user-images.githubusercontent.com/46418596/197148874-a8eaf1a2-ae6b-4bda-b9fa-23173e9b87c2.png">

**Comment by priority3** [comment]
> > 
> 
> The only way to register global components is to load OnuResolver with resolvers from vue-components. Obviously that's not reasonable. I think this only works as an onu-ui's ability to load components on demand, and global registration of components should succeed without configuring it.
> 
> <img alt="image" width="910" src="https://user-images.githubusercontent.com/46418596/197148874-a8eaf1a2-ae6b-4bda-b9fa-23173e9b87c2.png">

I find the question, because `components` are not completely exported, and I think that there are some problems with naming,  I will fix it later🤔
