### ISSUE TITLE
[BUG]: pnpm run play 失败

### ISSUE THREAD

**Issue by chenjz08** [onu-ui/onu-ui#78]
### Describe the bug

我用```ni```安装完项目依赖，执行```nr play```后，显示以下报错：
![image](https://user-images.githubusercontent.com/35839751/192964692-12672a0e-5c53-4534-91f4-efdeef788c6b.png)

我发现在```packages/components```、```packages/onu-ui```和```packages/preset```中，并没有`build`生成的`dist`文件夹，所以我分别在这三个项目中去执行`build`生成`dist`。然后再执行`nr play`,结果显示另外一个错误。如下图所示：
![image](https://user-images.githubusercontent.com/35839751/192965906-0c592b15-7aca-4d6d-a769-07aba070efda.png)

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
    Memory: 3.27 GB / 15.72 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.53)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vue: ^3.2.39 => 3.2.39
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/onu-ui/onu-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://onu-ui.vercel.app/).
- [X] Check that there isn't [already an issue](https://github.com/onu-ui/onu-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a OnuUI issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chenjz08** [comment]
![image](https://user-images.githubusercontent.com/35839751/192970001-fca595ea-a344-406c-9d46-1d1b8324f4d3.png)

**Comment by zyyv** [comment]
试试在顶层目录 `nr build` 然后 `nr play`。我们的工作流不太好，可能会打消你的积极性，抱歉。

**Comment by chenjz08** [comment]
按照你的方法解决问题了，非常感谢解答。
