### ISSUE TITLE
[Bug]: HMR in dev server

### ISSUE THREAD

**Issue by zyyv** [onu-ui/onu-ui#9]
当我在开发环境中开发时`(pnpm run dev)`，我使用了`vite build --watch` 和 `tsup --watch`去监听多个 package 文件内更新进而重新打包，以方便`playground`进行开发环境的实时预览。
但是现在即时我开始 watch 模式，控制台也重新打包了，但是`playground` 并没有得到及时更新，我需要手动去执行`pnpm run build`，使`playground`的依赖发生变更，才会使 playground 拥有热更新。

有大神帮我解决一下问题吗？万分感谢🙏

ex: 
<img width="716" alt="image" src="https://user-images.githubusercontent.com/42139754/184523235-6f7b4bec-42f4-4356-942e-373d3f92db6c.png">

<img width="667" alt="image" src="https://user-images.githubusercontent.com/42139754/184523263-50cf6253-f538-48b1-aa6a-474b35db5936.png">

**Comment by Brain777777** [comment]
@chris-zhu 在 playground 中使用  `dev: vite --force`  让 vite 不使用缓存

**Comment by zyyv** [comment]
> @chris-zhu 在 playground 中使用 `dev: vite --force` 让 vite 不使用缓存

谢谢你的回复，尝试过了，还是没有起作用。我不知道 playground 的 node_modules 的依赖如何随着packages 里面的 watch 的更新 也自动更新😭

**Comment by Brain777777** [comment]
@chris-zhu 😹 我看了好久才发现原来这个问题是需要 preset 改动后触发更新，我当时以为是 packages 中其他包的改动然后需要触发更新。 如果是 preset 触发更新的话，那就必须要重新运行命令。因为 preset 是在 vite config 中使用。
